### ISSUE TITLE
Resource package not available on Windows and figures can not be updated 

### ISSUE THREAD

**Issue by ZilH** [Pecnut/stokesian-dynamics#7]
I am on a Windows 10 machine. 

The Resource package is only on Linux so i have to comment out to make it run. 

In addition, when view_graphics = True, the figures will freeze on the first frame causing the run_simulation.py crash. view_graphics = False solve the problem.

**Comment by Pecnut** [comment]
Hi @ZilH. Thanks for your comments re Windows 10. I have switched away from the resource package so that the latest version should now run happily on Windows.

I'm not able to reproduce the first frame freezing problem but let me know if that's still happening. In general, I think it's best to run the software with `view_graphics = False` and then to visualise the results later, but in the early days of playing with Stokesian Dynamics I think it's nice to be able to see what's going on, which is why it's on by default.

The latest update is pretty substantial in terms of file structure changes, which I think makes the code clearer, but "upgrading" might be more awkward. There is very little different in terms of file content changes; I've just put things in folders so the codes are less cluttered.
